version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword   # 루트 비밀번호
      MARIADB_DATABASE: mydatabase          # 기본 생성할 DB 이름
      MARIADB_USER: myuser                  # 사용자 이름
      MARIADB_PASSWORD: mypassword          # 사용자 비밀번호
    ports:
      - "3390:3306"