spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:p6spy:mariadb://localhost:10035/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

p6spy:
  config:
    logMessageFormat: com.p6spy.engine.spy.appender.SingleLineFormat
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    databaseDialectDateFormat: yyyy-MM-dd HH:mm:ss
    dateFormat: yyyy-MM-dd HH:mm:ss
    logLevel: info
    realdriver: com.mysql.cj.jdbc.Driver
